#!/bin/bash
#
# log_scan web app for log scan service (https://github.com/nuwadb/log_scan.git)
#
# chkconfig: - 90 10
# description: Schedule file scan jobs.


. /etc/rc.d/init.d/functions

USER="lvdb"
DAEMON="/opt/node/bin/node"
ROOT_DIR="/opt/lvdb/node/log_scan"

SERVER="$ROOT_DIR/app.js"
#LOG_FILE="$ROOT_DIR/app.js.log"
PROG="log_scan"
LOCK_FILE="/var/lock/subsys/$PROG"

do_start()
{
#        if [ ! -f "$LOCK_FILE" ] ; then
      
         echo -n $"Starting $SERVER: "
                #daemon --user lvdb "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
         daemon --user lvdb "$DAEMON $SERVER 2>&1 | logger -t $PROG &" && echo_success || echo_failure
         RETVAL=$?
         echo
         [ $RETVAL -eq 0 ] && touch $LOCK_FILE
#        else
#                echo "$SERVER is locked."
#                RETVAL=1
#        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
exit $RETVAL
